remove puiPortfolio.html file due to failed build
Fetching submodules
  /usr/bin/git submodule sync --recursive
  /usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
  Error: fatal: No url found for submodule path 'images/PUITA/work/esaltz' in .gitmodules
  Error: The process '/usr/bin/git' failed with exit code 128